DROP TABLE IF EXISTS CreditCard;
DROP TABLE IF EXISTS Payment;
DROP TABLE IF EXISTS PayTransaction;

CREATE TABLE CreditCard (
  cardNum BIGINT PRIMARY KEY,
  encCardInfo VARBINARY(64) NOT NULL,
  lastPayDate DATETIME NOT NULL,
  version INT NOT NULL
);

CREATE TABLE Payment (
  paymentId CHAR(20) PRIMARY KEY,
  cardNum BIGINT NOT NULL,
  payDate DATETIME NOT NULL,
  remainAmount BIGINT NOT NULL,
  remainTax BIGINT NOT NULL,
  orgAmount BIGINT NOT NULL,
  orgTax BIGINT NOT NULL,
  version INT NOT NULL
);

CREATE TABLE PayTransaction (
  seqNo BIGINT AUTO_INCREMENT PRIMARY KEY,
  paymentId CHAR(20) NOT NULL,
  type VARCHAR(20) NOT NULL,
  transactionDate DATETIME NOT NULL,
  amount BIGINT NOT NULL,
  tax BIGINT NOT NULL,
  remainAmount BIGINT NOT NULL,
  remainTax BIGINT NOT NULL
);